
excluded:
  - Tests/GzipTests

opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - implicit_return
  - implicitly_unwrapped_optional
  - let_var_whitespace
  - multiline_parameters
  - nimble_operator
  - no_extension_access_modifier
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - private_outlet
  - redundant_nil_coalescing
  - strict_fileprivate
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

trailing_comma:
  mandatory_comma: true

trailing_whitespace:
  ignores_empty_lines: true

vertical_whitespace:
  max_empty_lines: 2

line_length: 200
