name: Test

on: [push, pull_request]

jobs:
  macOS:
    name: Test on macOS
    runs-on: macos-26
    env:
      DEVELOPER_DIR: /Applications/Xcode_26.4.app
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Show environments
      run: |
        swift --version
        xcodebuild -version
    - name: Lint Swift
      run: |
        if [[ ! -f "/usr/local/bin/swiftlint" ]]; then
            brew install swiftlint
        fi
        swiftlint
    - name: Unit Test
      run: |
        swift test
  iOS:
    name: Test on iOS
    runs-on: macos-26
    env:
      DEVELOPER_DIR: /Applications/Xcode_26.4.app
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Show environments
      run: |
        swift --version
        xcodebuild -version
    - name: Unit Test
      run: |
        xcodebuild test \
          -scheme GzipSwift \
          -destination 'platform=iOS Simulator,name=iPhone 17,OS=latest'
  linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    container: swift:latest
    steps:
    - uses: actions/checkout@v5
    - name: Unit Test
      run: swift test --enable-swift-testing
